server {
    listen 8000;
    server_name fft;
    root /var/www/html/browser;
    index index.html;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_min_length 256;
    
    gzip_types
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/xml
        font/eot
        font/otf
        font/ttf
        image/svg+xml
        text/css
        text/javascript
        text/plain
        text/xml;

    access_log off;
    error_log /var/log/nginx/error.log crit;

    proxy_read_timeout 24h;

    location ~ /index.html|.*\.json$ {
        expires -1;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    }

    location ~ /.*\.(?:css|js|ttf|woff|woff2|eot|svg|jpe?g|png|gif|ico|webp|avif)(?:\.map)?$ {
        expires 1y;
    }

    location / {
        try_files $uri$args $uri$args/ /index.html;
    }
}
